
exp_name: sps-single-branch
dataset: cub
train_proc: comm
test_proc: comm

midlevel: True
prams_group: ['ftlayer','freshlayer']
lr_group: [0.001,0.01]
lrstep: [40,70]
lrgamma: 0.1
detach_epoch: 60
epochs: 160
numswap: 3
sp: [[0.3,0.5]]


criterion: CrossEntropyLoss
reduction: none
warp: True
